server:
  port: 9091
spring:
  application:
    name: sleuth-testservice1
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.132.33.43:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
