server:
  port: 9092
spring:
  application:
    name: sleuth-testservice2
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.132.33.43:8761/eureka/
